# Generated by Django 4.2 on 2023-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_remove_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
